In [1]:
import os
from datetime import datetime
import pandas as pd

from optionStrategies import long_call, short_call, long_call_long_put, long_call_short_put
from data_import import get_data
from tradeStat import results
from pathlib import PurePath, Path

pp = PurePath(Path.cwd()).parts[:]
pdir = PurePath(*pp)
infp=PurePath(pdir)

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
infp

PureWindowsPath('C:/Users/rex.wong/Documents/Project2_options_1213/Project2_options')

In [2]:
MARKET = "ASX"
EVENT = "DOMESTIC_ELECTION" 
NUM_FILE = 1
RETURN_THRE = 0

# after the result
path_after = os.path.join(infp , "Result" , MARKET , MARKET +"_" + EVENT , "after")

In [3]:
entries = os.listdir(path_after)
NKY_FED_after = pd.DataFrame()

for entry in entries[:NUM_FILE]:
    xls_file = os.path.join(path_after, entry)
    df = pd.read_excel(xls_file)
    NKY_FED_after = NKY_FED_after.append(df, ignore_index = True)

df_after = NKY_FED_after.drop(["trade_num", "entry_gamma","total_t_cost"], axis = 1)

In [4]:
df_after[df_after['Average_Daily_Return_pct'] > RETURN_THRE]

  entry_date  exit_date maturity_date  entry_delta  entry_vega  entry_rho  entry_theta  entry_price  exit_price  holding_period  num_contracts  Actual_Profit  Average_Day_Profit  Total_Return_pct  Average_Daily_Return_pct
2 2016-06-28 2016-07-04    2016-07-21         0.00       10.20      -0.13        -4.50       -20790       24270               6              5          17300             2883.33             17.30                      2.88
3 2016-06-28 2016-07-04    2016-08-18        -0.01       15.12      -0.45        -2.96       -30360       31690               6              3           3930              655.00              3.93                      0.66
4 2016-06-29 2016-07-04    2016-07-21        -0.04       10.04      -0.23        -4.24       -18720       20920               5              5          10900             2180.00             10.90                      2.18
5 2016-06-29 2016-07-04    2016-08-18         0.00       15.08      -0.44        -2.82       -29680       31140               5              3           4320              864.00              4.32                      0.86

In [5]:
df_after[df_after['Average_Daily_Return_pct'] < -RETURN_THRE]

  entry_date  exit_date maturity_date  entry_delta  entry_vega  entry_rho  entry_theta  entry_price  exit_price  holding_period  num_contracts  Actual_Profit  Average_Day_Profit  Total_Return_pct  Average_Daily_Return_pct
0 2016-06-27 2016-07-04    2016-07-21        -0.01       10.47      -0.17        -4.67       -23820       22990               7              4          -3400             -485.71             -3.40                     -0.49
1 2016-06-27 2016-07-04    2016-08-18        -0.01       15.37      -0.54        -3.00       -32730       31140               7              3          -4830             -690.00             -4.83                     -0.69
6 2016-06-30 2016-07-04    2016-07-21         0.02        9.98      -0.05        -4.20       -17720       17110               4              6          -3780             -945.00             -3.78                     -0.94
7 2016-06-30 2016-07-04    2016-08-18         0.00       15.20      -0.36        -2.73       -26910       26680               4              4          -1000             -250.00             -1.00                     -0.25
8 2016-07-01 2016-07-04    2016-07-21        -0.02        9.77      -0.17        -4.17       -16730       16260               3              6          -2940             -980.00             -2.94                     -0.98
9 2016-07-01 2016-07-04    2016-08-18         0.00       15.08      -0.36        -2.74       -27810       27640               3              4           -760             -253.33             -0.76                     -0.25

In [6]:
# large return, short hoding period
df_after[(abs(df_after['Average_Daily_Return_pct']) > RETURN_THRE) &  (df_after['holding_period'] < 4)]

  entry_date  exit_date maturity_date  entry_delta  entry_vega  entry_rho  entry_theta  entry_price  exit_price  holding_period  num_contracts  Actual_Profit  Average_Day_Profit  Total_Return_pct  Average_Daily_Return_pct
8 2016-07-01 2016-07-04    2016-07-21        -0.02        9.77      -0.17        -4.17       -16730       16260               3              6          -2940             -980.00             -2.94                     -0.98
9 2016-07-01 2016-07-04    2016-08-18         0.00       15.08      -0.36        -2.74       -27810       27640               3              4           -760             -253.33             -0.76                     -0.25

In [7]:
abs(df_after['Average_Daily_Return_pct']).mean()

1.0180000000000002

In [8]:
print("Exit after the event:", df_after[(df_after['holding_period'] < 4)]['Average_Daily_Return_pct'].mean())
print("Exit afterthe event:", df_after[(df_after['holding_period'] < 4)]['Average_Daily_Return_pct'].std())

Exit after the event: -0.615
Exit afterthe event: 0.5161879502661797